Repository HowlingByte/Marmit65, pull requests merged in 2023-05, with the labels that each got.

#18 🎬Add scale change on slideIn keyframes
  style.css
Labels: enhancement

#19 🔗Change Github Link
  404.html
  accueil.html
  contact.html
  famille.html
  mentions.html
  recette.html
  template/accueil.tpl
  template/contact.tpl
  template/mentions.tpl
Labels: enhancement

#21 🏦Update BDD (Foreign key)
  marmita.db
  marmita.db.sql
Labels: bug

#22 💻Modification fonction pour utiliser les classes
  main.py
Labels: bug

#30 🍔Ajout ingrédients page recette
  template/recette.tpl
Labels: enhancement

#39 :bug: Lien footer
  template/recette.tpl
Labels: bug

#43 🔧 Formatage autopep8
  .vscode/settings.json
  main.py
  template/chercheRecettes.tpl
  template/recette.tpl
Labels: enhancement

#46 📎 Add link badge of README
  README.md
Labels: documentation

#51 [DO NO MERGE] 📱Mobile Version enhancement
  static/css/style.css
  static/html/contact.html
  template/accueil.tpl
  template/chercheRecettes.tpl
  template/famille.tpl
  template/recette.tpl
Labels: enhancement

#53 🔧 Transformer en int si entier dans la page ingredients
  main.py
Labels: bug

#65 :bug: Correctif sur les fonts
  static/css/fonts.css
Labels: bug

#67 :bug: Ajout d'une erreur 404 lorsque TypeError sur les pages famille ou recette
  main.py
Labels: bug

#68 :wrench: Changements mineurs sur le css
  main.py
  static/css/style.css
Labels: enhancement
